"""Tests for :mod:`deltasuite.core.config_files`."""

from __future__ import annotations

from pathlib import Path

import pytest

from deltasuite.core.config_files import (
    ConfigDocument,
    ConfigFormat,
    detect_format,
    parse_mdf,
    parse_mdu,
    serialize_mdf,
    serialize_mdu,
)

# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------


def test_detect_format_known() -> None:
    assert detect_format(Path("foo.mdf")) is ConfigFormat.MDF
    assert detect_format(Path("foo.MDU")) is ConfigFormat.MDU


def test_detect_format_unknown() -> None:
    with pytest.raises(ValueError, match="Unsupported"):
        detect_format(Path("foo.txt"))


# ---------------------------------------------------------------------------
# .mdu parsing / serialisation
# ---------------------------------------------------------------------------


_MDU_SAMPLE = """\
# generated by Delft3D-FM tools
[General]
Program          = D-Flow FM
Version          = 1.2.105.66483

[Geometry]
NetFile          = mesh.nc
WaterLevIniFile  =                                # leave empty
BedLevType       = 3

[Numerics]
CFLMax           = 0.7
"""


def test_parse_mdu_sections_and_keys() -> None:
    doc = parse_mdu(_MDU_SAMPLE)
    assert [s.name for s in doc.sections] == ["General", "Geometry", "Numerics"]
    assert doc.get("General", "Program") == "D-Flow FM"
    assert doc.get("Numerics", "cflmax") == "0.7"


def test_parse_mdu_preserves_comment() -> None:
    doc = parse_mdu(_MDU_SAMPLE)
    waterlev = doc.section("Geometry").get("WaterLevIniFile")  # type: ignore[union-attr]
    assert waterlev is not None
    assert "leave empty" in waterlev.comment


def test_mdu_roundtrip(tmp_path: Path) -> None:
    target = tmp_path / "case.mdu"
    target.write_text(_MDU_SAMPLE, encoding="utf-8")
    doc = ConfigDocument.load(target)
    doc.set("Numerics", "CFLMax", "0.95")
    out = tmp_path / "case_out.mdu"
    doc.save(out)
    payload = out.read_text(encoding="utf-8")
    assert "CFLMax           = 0.95" in payload
    re_parsed = parse_mdu(payload)
    assert re_parsed.get("Numerics", "CFLMax") == "0.95"


def test_serialize_mdu_appends_new_key() -> None:
    doc = parse_mdu(_MDU_SAMPLE)
    doc.set("Numerics", "MaxIter", "200")
    payload = serialize_mdu(doc)
    assert "MaxIter" in payload
    assert "200" in payload


# ---------------------------------------------------------------------------
# .mdf parsing / serialisation
# ---------------------------------------------------------------------------


_MDF_SAMPLE = """\
* sample mdf header
Ident   = #Delft3D-FLOW 4.05.00#
Runtxt  = #This is a test#
          #Second line#
Filcco  = #grid.grd#
Tstart  = 0.0
Tstop   = 1440.0
Dt      = 5.0
"""


def test_parse_mdf_flat() -> None:
    doc = parse_mdf(_MDF_SAMPLE)
    assert len(doc.sections) == 1
    assert doc.get("", "Ident") == "#Delft3D-FLOW 4.05.00#"
    assert doc.get("", "Tstop") == "1440.0"


def test_parse_mdf_continuation_line() -> None:
    doc = parse_mdf(_MDF_SAMPLE)
    runtxt = doc.get("", "Runtxt")
    assert runtxt is not None
    assert "Second line" in runtxt


def test_mdf_roundtrip(tmp_path: Path) -> None:
    target = tmp_path / "case.mdf"
    target.write_text(_MDF_SAMPLE, encoding="utf-8")
    doc = ConfigDocument.load(target)
    doc.set("", "Dt", "2.5")
    out = tmp_path / "case_out.mdf"
    doc.save(out)
    payload = out.read_text(encoding="utf-8")
    assert "Dt" in payload
    assert "2.5" in payload


def test_serialize_mdf_preserves_comments() -> None:
    doc = parse_mdf(_MDF_SAMPLE)
    payload = serialize_mdf(doc)
    assert "* sample mdf header" in payload
